export interface Itvshowdata {
  show:{
    name:string,
    language:string
    genres:string[],
    runtime:number,
    premiered:Date,
    schedule:{
      time:string,
      days:string[]
    },
    rating:{
      average:number
    },
    network:{
      name:string,
      country:{
        name:string
      }
    },
    image:{
      orginal:string
    }
    summary:string,
    type:string,
    status:string
  },
}
